language: perl
perl:
- 5.18.2
sudo: required
services:
- docker
before_install:
- cpanm -n Devel::Cover::Report::Coveralls
install:
- cpanm --installdeps .
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
script:
- kb-sdk test | tee log.txt
- (! grep -e "done_testing() was not seen" -e "Looks like you failed" log.txt)
env:
  global:
  - secure: eo5rM8HDGYigxbLeHqctZy3+Wx/wyTNOl1wqnElxXEFmaZ94xEfEcnHTK+PTXkQOXSwoXG0mOmPZCuG1ZKhtU3qP71TivEukf5iKCR4FY0VwXNjFGgLH/XGIDQizphrQWxeh/yJHJHEt1MskcKUK9wfarmHCJE3Xnjg/1MqNiyIRkSgYhFTvg6Vsi9bUvsjkslUZ7PsaRtL4Hu3ktalc8oDd4Y953ByjfZBZpiva2f+eydn2Dh1jE74p3rN6EdXK6gDSHQz6gFbBzzlJCX9AcWf3WxPaotBCpm1IrUcMt2EeWPDFTFCCRiRzWd/+AvdUwFxGpmFzDS8Enf442by4j+cuFzUqRnYESqPcVBM903vcuZVGH1tDEjk50eOLXmOOyf6/dSqbCduYAXGCFLHiX1Dd5VLdjYkFp4chR1ZmGrDrslAsqm1uBH+PdVbzghuRLU0jhTnWEO+eOuo8aapILkmjZRSRfEYsSZ2PpQP4oZddYkEOIUaal1yhUUluoSg8HVFM65LL2eswkSSGUVxIP59xtN/sh95zi/M9WUp0cRXLB+OxWcFrqPL30rV472IiWUiIYLRj08YtmoycxYiqJ2OSQUqWOeBJEUEFVzPm71rcNZGDd+P4d46teGVzxdN1Dm6OUSkAehEfr7B5YVwB/+AoEW9z6qC/KIzckY9XqD8=
  - secure: AD+BIaCCt44eamSL4Ds69ZFm3nPAx5ImwnyPhXNbk/Ji0gFerJxctZ0RuHT0Rb7kd8IgYvdlvoX3J5HEJdmC/aYnW2QkfKyig9aAJj/ffQzmFkOPi5Zv+Auf3bRh5/QTpKvt2oaXwvHse0VqrRMr/7oeKHbHIEs5UewLNxGwGdDUC9g3w5S2wmosBBgheav5phgUBx4h+ZrjgRCf0bSm1xDnUINB0uwQFjj9J60apNBSWB++VLG7mMW8g8HMyfdX6USP+9ZewNC96JJlQ7rxPqAkWRiXRA7jhIhm0TmB/2M3xE7I1XfXEG9XkPcvaH2BpRFm4XhwPHLBM1EwE0HqXXkVpTJjfxXpCzJeFTzAXUikItdDTm0ENfCOvMSyPFrdTee0dzyK3dTL5/iqf3yUQVAhdWIzVZRM9we/3zWDeq95kdOTxI5K4o0VEZeg4K1DRGSxkYPm2XK3VQ4GXQe4pKexkbJmvU4fBoikWlmXRvYdeZvBaK+svD0+5CNABv9BgZPirfzXZCSya9cKGdYYQci19oS4X4Y6VyboaPZpbqHSC7RKyVfN84WQRW8q927CW6VnRgnxmCwwHWhTMrEGCAR1aKRIVqqDScbhHaB0vvg2lMioDW0d4Ah+n+jbEW2AhFt9YuOc7s0eXFINNRg9WoEf5FzTUxS1u3fNz3fpnuw=
