name: Docker Image CI

on:
  push:
    branches: [ compile_tests_ext ]
  pull_request:
    branches: [ master ]

jobs:

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ialarmedalien/fba_tools:$(date +%s)

  install_kbsdk_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2
        
    - name: install kb-sdk
      env:
        PATH: ${{ env.PATH }}:./bin/kb-sdk
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        chmod +x ./scripts/kb_sdk_prep.sh
        ./scripts/kb_sdk_prep.sh
        kb-sdk test
