name: Docker Image CI

on:
  push:
    branches: [ compile_tests_ext ]
  pull_request:
    branches: [ master ]

jobs:

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ialarmedalien/fba_tools:$(date +%s)

  install_kbsdk_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2
        
    - name: pull and run docker image
      shell: bash
      run: |
        docker pull kbase/kb-sdk
        docker run kbase/kb-sdk genscript > ./bin/kb-sdk
        chmod 755 ./bin/kb-sdk
        ./bin/kb-sdk version
    
    - name: change permissions
      shell: bash
      run: |
        chmod 755 ./bin/kb-sdk
        ./bin/kb-sdk version
      
    - name: run kb-sdk test
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: ./bin/kb-sdk test
