name: Docker Image CI

on:
  push:
    branches: [ compile_tests_ext ]
  pull_request:
    branches: [ master ]

jobs:

 build_test_local:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Build the Docker image
     run: docker build . --file Dockerfile --tag test/fba_tools:latest
   - name: Run tests
     run: docker run test/fba_tools:latest test
