name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  make_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make and test
      run: |
        make
        docker pull kbase/kb-sdk
        docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
        chmod 755 $HOME/bin/kb-sdk
        export PATH=$PATH:$HOME/bin/kb-sdk
        kb-sdk test
